---
pre-commit:
  stage: test
  image: registry.gitlab.com/winny/pre-commit-docker:latest
  variables:
    PRE_COMMIT_HOME: .pre-commit-cache
  cache:
    - key:
        files: [.pre-commit-config.yaml]
      paths: ['${PRE_COMMIT_HOME}']
  script:
    - pre-commit run -a
build image:
  stage: test
  image: docker:cli
  dependencies:
    - pre-commit  # Don't bother building image if pre-commit fails.
  services:
    - docker:dind
  script:
    - ./scripts/build.sh
push image:
  only:
    - master
  stage: deploy
  dependencies:
    - build image
  image: docker:cli
  services:
    - docker:dind
  script:
    # https://docs.gitlab.com/ee/user/packages/container_registry/authenticate_with_container_registry.html
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./scripts/push.sh
